# Generated by Django 3.0.6 on 2020-12-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Store Owner'),
        ),
    ]
