# Generated by Django 3.0.6 on 2021-01-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_ownerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='is_owner',
        ),
    ]
