# Generated by Django 3.0.6 on 2020-12-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201220_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products-img'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
