# Generated by Django 3.0.6 on 2020-12-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
