# Generated by Django 3.0.6 on 2020-12-20 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201221_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator('0.1')]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to='Products-images'),
        ),
    ]
