# Generated by Django 3.0.6 on 2020-12-20 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201221_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(58)]),
        ),
    ]
