# Generated by Django 3.0.6 on 2020-12-20 23:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201221_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('White', '#FFFFFF'), ('Sliver', '#C0C0C0'), ('Gray', '#808080'), ('Black', '#000000'), ('Red', '#FF0000'), ('Yellow', '#FFFF00'), ('Green', '#008000'), ('Blue', '#0000FF'), ('Purple', '#800080')], max_length=52, null=True),
        ),
    ]
