# Generated by Django 3.0.6 on 2020-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201221_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
