# Generated by Django 3.0.6 on 2020-12-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
