# Generated by Django 3.0.6 on 2020-12-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20201224_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storetype',
            options={'ordering': ['name']},
        ),
    ]
