# Generated by Django 3.0.6 on 2020-12-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20201224_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.TextField(max_length=1000),
        ),
    ]
