# Generated by Django 3.0.6 on 2020-12-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20201224_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at']},
        ),
    ]
