# Generated by Django 3.0.6 on 2021-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210105_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color_Choiced',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='size_Choiced',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
